### ISSUE TITLE
which is the correct stable branch for lx2160a?

### ISSUE THREAD

**Issue by aep** [SolidRun/linux-stable#5]
Hi, i stumbled onto this without any context.

which branch is actually working?
i tried several but they're all unusably slow and filling tty with
```
[  148.617348] arm-smmu arm-smmu.0.auto: Unhandled context fault: fsr=0x402, iova=0x2fe0000100, fsynr=0x210040, cbfrsynra=0x4000, cb=6
```

**Comment by jnettlet** [comment]
Do you mean LTS branch?  Currently there is an unfortunate divergence due to a change in the ACPI spec that deprecated an earlier revision of the IORT RMR specs.  We were the only implementation actually using the spec before the amendment.  If you are using a UEFI firmware released before July 1st 2021 then 5.10.y-cex7 is the proper branch to work with that firmware.  If you are using a latest firmware release (which I highly recommed due to some performance fixes as well as other bug fixes and the update to the latest IORT RMR specs) then you can use 5.10.y-cex7-latest, or the 5.12.y-cex7.  Beyond 5.12, there have been some changes in the linux kernel that have introduced bugs that we are working on sorting out with the mainline maintainers.  Or you can boot with `arm-smmu.disable_bypass=0` on the kernel commandline

**Comment by aep** [comment]
@jnettlet 

5.10.y-cex7-latest does boot thanks.
however, there is no documentation on how to enable ethernet.

restool doesnt work with this kernel

```
ls-addni dpmac.9 
MC error: Unsupported operation (status 0xb)
```

i guess a different userspace is required for uefi kernels?

**Comment by jnettlet** [comment]
you need to use one of the latest restool branches.  The edk2 firmware has upgraded the mcbin firmware to the latest version in edk2-non-osi.

**Comment by aep** [comment]
which branch would that be? neither master nor  "lx2160a-early-access" compile.
i tried using LSDK-20.12 which is the biggest number at least.

**Comment by jnettlet** [comment]
I am using the tag lf-5.10.35-2.0.0

**Comment by aep** [comment]
thanks. that doesnt work either.  


https://github.com/SolidRun/lx2160a_uefi  master  81b4bbe7d7100dbf31e6c64dbda3a0c8e6f585ee
https://github.com/SolidRun/linux-stable/   linux-5.10.y-cex7-latest   1aed2de7ab6ae6dbd391ad25ae935159d94d4f51
https://source.codeaurora.org/external/qoriq/qoriq-components/restool  lf-5.10.35-2.0.0 8fd3a6b3ba28a6d980a612f2064e6f8827744bcd

**Comment by jnettlet** [comment]
Can you please provide your output of dmesg?

**Comment by aep** [comment]
full log attached.

this seems relevant:

```
[    4.866111] fsl_mc_bus NXP0008:00: MC firmware version: 10.20.4
[    4.877759] fsl_mc_dprc dprc.1: DMA mask not set
[    4.957621] fsl_mc_dpio dpio.15: probed
[    4.967127] fsl_mc_dpio dpio.14: probed
[    4.976557] fsl_mc_dpio dpio.13: probed
[    4.986085] fsl_mc_dpio dpio.12: probed
[    4.995629] fsl_mc_dpio dpio.11: probed
[    4.996079] usb 4-1: new SuperSpeed Gen 1 USB device number 2 using xhci-hcd
[    5.005082] fsl_mc_dpio dpio.10: probed
[    5.016039] fsl_mc_dpio dpio.9: probed
[    5.025069] fsl_mc_dpio dpio.8: probed
[    5.034578] fsl_mc_dpio dpio.7: probed
[    5.044032] fsl_mc_dpio dpio.6: probed
[    5.049470] hub 4-1:1.0: USB hub found
[    5.053071] fsl_mc_dpio dpio.5: probed
[    5.053252] hub 4-1:1.0: 4 ports detected
[    5.062603] fsl_mc_dpio dpio.4: probed
[    5.072064] fsl_mc_dpio dpio.3: probed
[    5.081075] fsl_mc_dpio dpio.2: probed
[    5.090582] fsl_mc_dpio dpio.1: probed
[    5.100047] fsl_mc_dpio dpio.0: probed
[    5.107147] fsl_mc_dprc dprc.1: DPRC device bound to driver

```

[dmesg.txt](https://github.com/SolidRun/linux-stable/files/6955072/dmesg.txt)

**Comment by jnettlet** [comment]
That is the issue.  That is an older version of the mc-bin firmware which would require an older version of restool.  The latest is
`fsl_mc_bus NXP0008:00: MC firmware version: 10.28.1`

https://github.com/SolidRun/edk2-non-osi/commit/c4f571fe0da70cafc58b90342a766da854e71572

**Comment by aep** [comment]
errr. how do i update the mc-bin? i was assuming its automatically loaded by uefi firmware

**Comment by jnettlet** [comment]
It looks like there is an issue with the edk2-non-osi repository.  I will push fixes.  Thanks for helping me debug this issue.  give me an hour

**Comment by aep** [comment]
@jnettlet thanks! restool/eth is working now, but usb is now broken.


```
[   65.817277] xhci-hcd PNP0D10:01: ERROR unknown event type 37
[   65.817280] xhci-hcd PNP0D10:01: ERROR mismatched command completion event
[   65.817283] xhci-hcd PNP0D10:01: ERROR mismatched command completion event
```

**Comment by jnettlet** [comment]
I just downloaded the latest firmware from our CI and tested here against 5.10.y-cex-latest and did not see any usb errors.  Are you seeing any SMMU errors?

I will note that the only USB change with this release is the removal of a legacy _CID description, which is not longer used or needed.

**Comment by aep** [comment]
hard to see because dmesg gets spammed out immediately by usb errors.

this is from a boot that doesnt have that error, but instead
```
[  961.187396] cma: cma_alloc: alloc failed, req-size: 3 pages, ret: -12
```

[dmesg.txt](https://github.com/SolidRun/linux-stable/files/6959668/dmesg.txt)

**Comment by jnettlet** [comment]
Please increase your cma allocation to 64MB... Preferably 256MB which is
what most distro's default to.

**Comment by aep** [comment]
this made it work, thanks!
would be appreciated if there was a defconf that just worked. 

i'm just using the one from  lx2160a_build
maybe you can share yours?

**Comment by aep** [comment]
said that too early. it now fails later

```
[  129.077728] xhci-hcd PNP0D10:00: WARN: HC couldn't access mem fast enough for slot 1 ep 6
[  129.077743] r8152 2-1:1.0 enx00e111001632: intr status -63
[  129.125723] xhci-hcd PNP0D10:00: WARN: HC couldn't access mem fast enough for slot 1 ep 6
[  129.125737] r8152 2-1:1.0 enx00e111001632: intr status -63
[  129.221754] r8152 2-1:1.0 enx00e111001632: Stop submitting intr, status -71

```

**Comment by jnettlet** [comment]
Since SystemReady ES is designed to work with mainline distros I generally
recommend building with the distro's chosen config and only add the options
required for enabling the network complex.

For fedora this is simply adding the following to kernel-local

CONFIG_FSL_MC_BUS=y
CONFIG_FSL_MC_UAPI_SUPPORT=y

**Comment by jnettlet** [comment]
generally now it looks like you are hitting various reported XHCI bugs, mostly related to certain USB devices, with realtek NICs being some of the worst.  you can try adding `usbcore.autosuspend=-1` to the kernel command line to see if it helps.  But these issues are well documented in various kernel bug reports and not specific to Aarch64 or HC.

**Comment by aep** [comment]
i would, but the ubuntu 21.04 kernel  (5.11)  doesnt contain CONFIG_FSL_MC_UAPI_SUPPORT.
i would also try fedora, but they dont seem to have an uefi image: https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/aarch64/images/

**Comment by jnettlet** [comment]
For UEFI images in Fedora you use the standard installer.  https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/aarch64/iso/

Most the distros will still require a custom kernel for full functionality of the network complex, but the installers will work using either the full DVD image or a USB network adapter.  Then there are some other users that either have custom builds for the various distributions, or you can rebuild the kernel RPM adding the patches I have to the package, and config options, or use their various kernel packages.  I would recommend joining the discord server to touch base with the various distro work that is being done.

**Comment by nullr0ute** [comment]
> i would also try fedora, but they dont seem to have an uefi image: https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/aarch64/images/

Fedora only supports UEFI on aarch64 so there's no specific special UEFI image.
